image:
  repository: artifactory.dagility.com/docker/vdxap-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdxap-frontend-habitat-test-5.dagility.com
    paths:
    - /
serviceAccount:
  create: false
